<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Answer extends Model
{
    public function question() {
        return $this::belongsTo(Question::class);
    }

    public function user() {
        return $this::belongsTo(User::class);
    }

    public function getBodyHtmlAttribute() {
        return \Parsedown::instance()->text($this->body);
    }

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        //created là cho tạo xong save
        static::created(function($answer) {
            $answer->question->increment('answers_count');
            $answer->question->save();
        });
        //save là update xong save lại
//        static::saved(function($answer) {
//            echo 'Answer saved\n';
//        });
    }

    public function getCreatedDateAttribute() {
        return $this->created_at->diffForHumans();
    }
}
