<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Answer extends Model
{
    protected $fillable = ['body', 'user_id'];
    public function question() {
        return $this::belongsTo(Question::class);
    }

    public function user() {
        return $this::belongsTo(User::class);
    }

    public function getBodyHtmlAttribute() {
        return \Parsedown::instance()->text($this->body);
    }

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        //created là cho tạo xong save
        static::created(function($answer) {
            $answer->question->increment('answers_count');
        });
        //save là update xong save lại
//        static::saved(function($answer) {
//            echo 'Answer saved\n';
//        });

        static::deleted(function($answer) {
            $question = $answer->question;
            $question->decrement('answers_count');
//            if ($question->best_answer_id === $answer->id) {
//                $question->best_answer_id = NULL;
//                $question->save();
//            }
            //Tao foreigh key roi
        });
    }

    public function getCreatedDateAttribute() {
        return $this->created_at->diffForHumans();
    }

    public function getStatusAttribute() {
        return $this->id === $this->question->best_answer_id ? 'color: red' : '';
    }

    public function getIsBestAttribute() {
        return $this->id === $this->question->best_answer_id;
    }
}
